source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyNewApp' do
  config = use_native_modules!

  # React Native Maps principal
  pod 'react-native-maps', path: '../node_modules/react-native-maps'

  # Subspec “generated” apuntando al podspec que trae el paquete NPM
  pod 'react-native-maps-generated',
      :podspec => File.join(
        __dir__,
        '..',
        'node_modules',
        'react-native-maps',
        'react-native-maps.podspec'
      )

  # Resto de módulos RN
  use_react_native!(
    path: config[:reactNativePath],
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )
    if installer.pods_project.targets.map(&:name).include?("RCT-Folly")
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
  end
end
