source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'  # desactiva Fabric & TurboModules

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

target 'MyNewApp' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps-generated', path: "#{rn_maps_path}/react-native-maps-generated.podspec"
  pod 'react-native-maps',           path: rn_maps_path

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false,    # esto solo afecta a use_react_native!
    :fabric_enabled    => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # , :ccache_enabled => true
    )
    if installer.pods_project.targets.map(&:name).include?('RCT-Folly')
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
  end
end
