platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace:      "MyNewApp.xcworkspace",
      scheme:         "MyNewApp",
      clean:          true,
      export_method:  "app-store",

      # Indica tu Team ID a Xcode al build (archive)
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']}",

      # Esto seguirá configurando el export .ipa correctamente
      export_team_id: ENV["APPLE_TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => "OcrProductos_Release_Profile"
        }
      }
    )

    upload_to_testflight
  end
end
