default_platform :ios

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace:      "MyNewApp.xcworkspace",
      scheme:         "MyNewApp",
      clean:          true,
      export_method:  "app-store",


      export_team_id: ENV["APPLE_TEAM_ID"],      # Team para exportar .ipa

      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => "OcrProductos_Release_Profile"
          # ^ el nombre exacto de tu provisioning profile (sin .mobileprovision)
        }
      }
    )

    upload_to_testflight
  end
end

