platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace:      "MyNewApp.xcworkspace",
      scheme:         "MyNewApp",
      clean:          true,
      export_method:  "app-store",

      # ① Firma Manual con tu perfil de distribución
      xcargs: [
        "DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']}",
        "CODE_SIGN_STYLE=Manual",
        "PRODUCT_BUNDLE_IDENTIFIER=#{ENV['APP_IDENTIFIER']}",
        "PROVISIONING_PROFILE_SPECIFIER=OcrProductos_Release_Profile"
      ].join(" "),

      # ② Export .ipa (ya mapea el mismo profile)
      export_team_id: ENV["APPLE_TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => "OcrProductos_Release_Profile"
        }
      }
    )
    upload_to_testflight
  end
end
